-- =========================================================
-- TOURISM360
-- COMPLETE DATABASE SCHEMA
-- Migration: 20260927
-- =========================================================

create extension if not exists pgcrypto;


-- =========================================================
-- 1. PROFILES
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  phone text,
  role text not null default 'TOURIST'
    check (role in (
      'TOURIST',
      'BUSINESS_OWNER',
      'TOUR_GUIDE',
      'TRAVEL_AGENT',
      'ADMIN',
      'SUPER_ADMIN'
    )),
  avatar_url text,
  preferences jsonb not null default '{}'::jsonb,
  budget text,
  interests text[] not null default '{}',
  language text default 'en',
  status text not null default 'ACTIVE'
    check (status in ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 2. DESTINATIONS
-- =========================================================

create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  state text,
  country text default 'India',
  description text,
  image_url text,
  tags text[] not null default '{}',
  latitude double precision,
  longitude double precision,
  source text,
  source_id text,
  source_type text,
  data_status text not null default 'ADMIN_VERIFIED'
    check (data_status in (
      'LIVE',
      'CACHED',
      'ADMIN_VERIFIED',
      'BUSINESS_SUBMITTED',
      'USER_GENERATED',
      'DEMO_SAMPLE'
    )),
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 3. LISTINGS
-- =========================================================

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  city text,
  destination_slug text,
  description text,
  address text,
  latitude double precision,
  longitude double precision,
  image_url text,
  images jsonb not null default '[]'::jsonb,
  price_indicative text,
  rating_indicative text,
  tags text[] not null default '{}',
  phone text,
  website text,
  opening_hours jsonb not null default '{}'::jsonb,
  owner_id uuid references public.profiles(id) on delete set null,
  source text,
  source_id text,
  source_type text,
  data_status text not null default 'ADMIN_VERIFIED'
    check (data_status in (
      'LIVE',
      'CACHED',
      'ADMIN_VERIFIED',
      'BUSINESS_SUBMITTED',
      'USER_GENERATED',
      'DEMO_SAMPLE'
    )),
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  status text not null default 'ACTIVE'
    check (status in (
      'ACTIVE',
      'INACTIVE',
      'HIDDEN'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 4. EVENTS
-- =========================================================

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  category text,
  title text not null,
  date_text text,
  start_at timestamptz,
  end_at timestamptz,
  venue text,
  city text,
  description text,
  image_url text,
  latitude double precision,
  longitude double precision,
  source text,
  source_id text,
  data_status text not null default 'ADMIN_VERIFIED'
    check (data_status in (
      'LIVE',
      'CACHED',
      'ADMIN_VERIFIED',
      'BUSINESS_SUBMITTED',
      'USER_GENERATED',
      'DEMO_SAMPLE'
    )),
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  status text not null default 'ACTIVE'
    check (status in (
      'ACTIVE',
      'HIDDEN',
      'CANCELLED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 5. TRIPS
-- =========================================================

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  user_email text,
  title text not null,
  destination text,
  days integer,
  budget text,
  status text not null default 'PLANNED'
    check (status in (
      'PLANNED',
      'ONGOING',
      'COMPLETED',
      'CANCELLED'
    )),
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 6. ITINERARIES
-- =========================================================

create table if not exists public.itineraries (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  day_number integer not null,
  title text,
  morning jsonb not null default '{}'::jsonb,
  afternoon jsonb not null default '{}'::jsonb,
  evening jsonb not null default '{}'::jsonb,
  route jsonb not null default '{}'::jsonb,
  hotel jsonb not null default '{}'::jsonb,
  transport jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 7. BOOKINGS
-- =========================================================

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  user_email text,
  item_type text not null,
  item_id text,
  item_title text,
  date_text text,
  guests integer default 1,
  status text not null default 'PENDING'
    check (status in (
      'PENDING',
      'CONFIRMED',
      'CANCELLED',
      'COMPLETED'
    )),
  payment_status text not null default 'PENDING'
    check (payment_status in (
      'PENDING',
      'PAID',
      'FAILED',
      'REFUNDED',
      'NOT_REQUIRED'
    )),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 8. REVIEWS
-- =========================================================

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  user_email text,
  item_type text not null,
  item_id text,
  item_title text,
  rating integer not null check (rating between 1 and 5),
  comment text,
  photos jsonb not null default '[]'::jsonb,
  moderation_status text not null default 'PENDING'
    check (moderation_status in (
      'PENDING',
      'APPROVED',
      'REJECTED'
    )),
  verified_booking boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 9. FAVORITES
-- =========================================================

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  user_email text,
  item_type text not null,
  item_id text not null,
  title text,
  city text,
  image_url text,
  created_at timestamptz not null default now(),
  unique(user_email, item_type, item_id)
);


-- =========================================================
-- 10. CONTACTS
-- =========================================================

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  status text not null default 'NEW'
    check (status in (
      'NEW',
      'READ',
      'IN_PROGRESS',
      'RESOLVED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 11. BUSINESSES
-- =========================================================

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete cascade,
  business_name text not null,
  business_type text,
  description text,
  address text,
  city text,
  state text,
  country text default 'India',
  phone text,
  email text,
  website text,
  documents jsonb not null default '{}'::jsonb,
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  status text not null default 'ACTIVE'
    check (status in (
      'ACTIVE',
      'INACTIVE',
      'SUSPENDED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 12. GUIDES
-- =========================================================

create table if not exists public.guides (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  bio text,
  languages text[] not null default '{}',
  services text[] not null default '{}',
  experience_years integer default 0,
  availability jsonb not null default '{}'::jsonb,
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 13. TRAVEL AGENCIES
-- =========================================================

create table if not exists public.travel_agencies (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete cascade,
  agency_name text not null,
  description text,
  address text,
  city text,
  state text,
  country text default 'India',
  phone text,
  email text,
  website text,
  verification_status text not null default 'PENDING'
    check (verification_status in (
      'PENDING',
      'VERIFIED',
      'REJECTED'
    )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 14. NOTIFICATIONS
-- =========================================================

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  type text default 'SYSTEM',
  is_read boolean not null default false,
  action_url text,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 15. RECOMMENDATIONS
-- =========================================================

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  item_type text not null,
  item_id text not null,
  reason text,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 16. AUDIT LOGS
-- =========================================================

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_email text,
  action text not null,
  resource_type text,
  resource_id text,
  status text default 'SUCCESS',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 17. ANALYTICS EVENTS
-- =========================================================

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_name text not null,
  resource_type text,
  resource_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);


-- =========================================================
-- 18. REPORTS
-- =========================================================

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references public.profiles(id) on delete set null,
  reporter_email text,
  resource_type text not null,
  resource_id text,
  reason text not null,
  description text,
  priority text not null default 'MEDIUM'
    check (priority in (
      'LOW',
      'MEDIUM',
      'HIGH',
      'CRITICAL'
    )),
  status text not null default 'OPEN'
    check (status in (
      'OPEN',
      'IN_REVIEW',
      'RESOLVED',
      'REJECTED'
    )),
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- 19. SAFETY ALERTS
-- =========================================================

create table if not exists public.safety_alerts (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  city text,
  state text,
  country text default 'India',
  severity text not null default 'INFO'
    check (severity in (
      'INFO',
      'WARNING',
      'CRITICAL'
    )),
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);


-- =========================================================
-- INDEXES
-- =========================================================

create index if not exists idx_destinations_slug
  on public.destinations(slug);

create index if not exists idx_destinations_state
  on public.destinations(state);

create index if not exists idx_destinations_data_status
  on public.destinations(data_status);

create index if not exists idx_listings_category
  on public.listings(category);

create index if not exists idx_listings_city
  on public.listings(city);

create index if not exists idx_listings_destination_slug
  on public.listings(destination_slug);

create index if not exists idx_listings_owner_id
  on public.listings(owner_id);

create index if not exists idx_listings_status
  on public.listings(status);

create index if not exists idx_events_city
  on public.events(city);

create index if not exists idx_events_status
  on public.events(status);

create index if not exists idx_trips_user_id
  on public.trips(user_id);

create index if not exists idx_bookings_user_id
  on public.bookings(user_id);

create index if not exists idx_reviews_user_id
  on public.reviews(user_id);

create index if not exists idx_reviews_item
  on public.reviews(item_type, item_id);

create index if not exists idx_favorites_user_email
  on public.favorites(user_email);

create index if not exists idx_businesses_owner_id
  on public.businesses(owner_id);

create index if not exists idx_guides_user_id
  on public.guides(user_id);

create index if not exists idx_agencies_owner_id
  on public.travel_agencies(owner_id);

create index if not exists idx_notifications_user_id
  on public.notifications(user_id);

create index if not exists idx_recommendations_user_id
  on public.recommendations(user_id);

create index if not exists idx_audit_logs_actor_id
  on public.audit_logs(actor_id);

create index if not exists idx_analytics_events_user_id
  on public.analytics_events(user_id);

create index if not exists idx_reports_reporter_id
  on public.reports(reporter_id);

create index if not exists idx_safety_alerts_active
  on public.safety_alerts(active);


-- =========================================================
-- UPDATED_AT FUNCTION
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- =========================================================
-- UPDATED_AT TRIGGERS
-- =========================================================

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists destinations_set_updated_at on public.destinations;
create trigger destinations_set_updated_at
before update on public.destinations
for each row execute function public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at
before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists trips_set_updated_at on public.trips;
create trigger trips_set_updated_at
before update on public.trips
for each row execute function public.set_updated_at();

drop trigger if exists bookings_set_updated_at on public.bookings;
create trigger bookings_set_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at
before update on public.contacts
for each row execute function public.set_updated_at();

drop trigger if exists businesses_set_updated_at on public.businesses;
create trigger businesses_set_updated_at
before update on public.businesses
for each row execute function public.set_updated_at();

drop trigger if exists guides_set_updated_at on public.guides;
create trigger guides_set_updated_at
before update on public.guides
for each row execute function public.set_updated_at();

drop trigger if exists travel_agencies_set_updated_at on public.travel_agencies;
create trigger travel_agencies_set_updated_at
before update on public.travel_agencies
for each row execute function public.set_updated_at();

drop trigger if exists reports_set_updated_at on public.reports;
create trigger reports_set_updated_at
before update on public.reports
for each row execute function public.set_updated_at();


-- =========================================================
-- AUTH PROFILE TRIGGER
-- =========================================================

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_name text;
  profile_role text;
begin

  profile_name :=
    coalesce(
      nullif(new.raw_user_meta_data ->> 'name', ''),
      split_part(new.email, '@', 1)
    );

  profile_role :=
    case
      when new.raw_app_meta_data ->> 'role'
        in ('ADMIN', 'SUPER_ADMIN')
        then new.raw_app_meta_data ->> 'role'

      when new.raw_user_meta_data ->> 'role'
        in ('BUSINESS_OWNER', 'TOUR_GUIDE', 'TRAVEL_AGENT')
        then new.raw_user_meta_data ->> 'role'

      else 'TOURIST'
    end;

  insert into public.profiles
  (
    id,
    email,
    name,
    role
  )
  values
  (
    new.id,
    new.email,
    profile_name,
    profile_role
  )
  on conflict (id)
  do update set
    email = excluded.email,
    name = excluded.name;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_auth_user();


-- =========================================================
-- RLS HELPER FUNCTIONS
-- =========================================================

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1;
$$;


create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('ADMIN', 'SUPER_ADMIN')
  );
$$;


-- =========================================================
-- ENABLE RLS
-- =========================================================

alter table public.profiles enable row level security;
alter table public.destinations enable row level security;
alter table public.listings enable row level security;
alter table public.events enable row level security;
alter table public.trips enable row level security;
alter table public.itineraries enable row level security;
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;
alter table public.contacts enable row level security;
alter table public.businesses enable row level security;
alter table public.guides enable row level security;
alter table public.travel_agencies enable row level security;
alter table public.notifications enable row level security;
alter table public.recommendations enable row level security;
alter table public.audit_logs enable row level security;
alter table public.analytics_events enable row level security;
alter table public.reports enable row level security;
alter table public.safety_alerts enable row level security;


-- =========================================================
-- PROFILES POLICIES
-- =========================================================

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin
on public.profiles
for select
using (
  id = auth.uid()
  or public.is_admin()
);

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin
on public.profiles
for update
using (
  id = auth.uid()
  or public.is_admin()
)
with check (
  (
    id = auth.uid()
    and role = (
      select p.role
      from public.profiles p
      where p.id = auth.uid()
    )
  )
  or public.is_admin()
);

drop policy if exists profiles_admin_insert on public.profiles;
create policy profiles_admin_insert
on public.profiles
for insert
with check (public.is_admin());

drop policy if exists profiles_admin_delete on public.profiles;
create policy profiles_admin_delete
on public.profiles
for delete
using (public.is_admin());


-- =========================================================
-- DESTINATIONS POLICIES
-- =========================================================

drop policy if exists destinations_public_select on public.destinations;
create policy destinations_public_select
on public.destinations
for select
using (
  data_status in (
    'LIVE',
    'CACHED',
    'ADMIN_VERIFIED',
    'BUSINESS_SUBMITTED',
    'USER_GENERATED',
    'DEMO_SAMPLE'
  )
);

drop policy if exists destinations_admin_insert on public.destinations;
create policy destinations_admin_insert
on public.destinations
for insert
with check (public.is_admin());

drop policy if exists destinations_admin_update on public.destinations;
create policy destinations_admin_update
on public.destinations
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists destinations_admin_delete on public.destinations;
create policy destinations_admin_delete
on public.destinations
for delete
using (public.is_admin());


-- =========================================================
-- LISTINGS POLICIES
-- =========================================================

drop policy if exists listings_public_select on public.listings;
create policy listings_public_select
on public.listings
for select
using (
  status = 'ACTIVE'
  and data_status in (
    'LIVE',
    'CACHED',
    'ADMIN_VERIFIED',
    'DEMO_SAMPLE'
  )
);

drop policy if exists listings_owner_insert on public.listings;
create policy listings_owner_insert
on public.listings
for insert
with check (
  owner_id = auth.uid()
  or public.is_admin()
);

drop policy if exists listings_owner_update on public.listings;
create policy listings_owner_update
on public.listings
for update
using (
  owner_id = auth.uid()
  or public.is_admin()
)
with check (
  owner_id = auth.uid()
  or public.is_admin()
);

drop policy if exists listings_owner_delete on public.listings;
create policy listings_owner_delete
on public.listings
for delete
using (
  owner_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- EVENTS POLICIES
-- =========================================================

drop policy if exists events_public_select on public.events;
create policy events_public_select
on public.events
for select
using (status = 'ACTIVE');

drop policy if exists events_admin_insert on public.events;
create policy events_admin_insert
on public.events
for insert
with check (public.is_admin());

drop policy if exists events_admin_update on public.events;
create policy events_admin_update
on public.events
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists events_admin_delete on public.events;
create policy events_admin_delete
on public.events
for delete
using (public.is_admin());


-- =========================================================
-- TRIPS POLICIES
-- =========================================================

drop policy if exists trips_owner_select on public.trips;
create policy trips_owner_select
on public.trips
for select
using (
  user_id = auth.uid()
  or user_email = (
    select email
    from public.profiles
    where id = auth.uid()
  )
  or public.is_admin()
);

drop policy if exists trips_owner_insert on public.trips;
create policy trips_owner_insert
on public.trips
for insert
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists trips_owner_update on public.trips;
create policy trips_owner_update
on public.trips
for update
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists trips_owner_delete on public.trips;
create policy trips_owner_delete
on public.trips
for delete
using (
  user_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- ITINERARIES POLICIES
-- =========================================================

drop policy if exists itineraries_trip_owner on public.itineraries;
create policy itineraries_trip_owner
on public.itineraries
for all
using (
  exists (
    select 1
    from public.trips t
    where t.id = trip_id
      and (
        t.user_id = auth.uid()
        or public.is_admin()
      )
  )
)
with check (
  exists (
    select 1
    from public.trips t
    where t.id = trip_id
      and (
        t.user_id = auth.uid()
        or public.is_admin()
      )
  )
);


-- =========================================================
-- BOOKINGS POLICIES
-- =========================================================

drop policy if exists bookings_owner_select on public.bookings;
create policy bookings_owner_select
on public.bookings
for select
using (
  user_id = auth.uid()
  or user_email = (
    select email
    from public.profiles
    where id = auth.uid()
  )
  or public.is_admin()
);

drop policy if exists bookings_owner_insert on public.bookings;
create policy bookings_owner_insert
on public.bookings
for insert
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists bookings_owner_update on public.bookings;
create policy bookings_owner_update
on public.bookings
for update
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists bookings_owner_delete on public.bookings;
create policy bookings_owner_delete
on public.bookings
for delete
using (
  user_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- REVIEWS POLICIES
-- =========================================================

drop policy if exists reviews_public_approved on public.reviews;
create policy reviews_public_approved
on public.reviews
for select
using (
  moderation_status = 'APPROVED'
  or user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists reviews_owner_insert on public.reviews;
create policy reviews_owner_insert
on public.reviews
for insert
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists reviews_owner_update on public.reviews;
create policy reviews_owner_update
on public.reviews
for update
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists reviews_owner_delete on public.reviews;
create policy reviews_owner_delete
on public.reviews
for delete
using (
  user_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- FAVORITES POLICIES
-- =========================================================

drop policy if exists favorites_owner_all on public.favorites;
create policy favorites_owner_all
on public.favorites
for all
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- CONTACTS POLICIES
-- =========================================================

drop policy if exists contacts_insert_public on public.contacts;
create policy contacts_insert_public
on public.contacts
for insert
with check (true);

drop policy if exists contacts_admin_select on public.contacts;
create policy contacts_admin_select
on public.contacts
for select
using (public.is_admin());

drop policy if exists contacts_admin_update on public.contacts;
create policy contacts_admin_update
on public.contacts
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists contacts_admin_delete on public.contacts;
create policy contacts_admin_delete
on public.contacts
for delete
using (public.is_admin());


-- =========================================================
-- BUSINESSES POLICIES
-- =========================================================

drop policy if exists businesses_owner_or_verified on public.businesses;
create policy businesses_owner_or_verified
on public.businesses
for select
using (
  owner_id = auth.uid()
  or verification_status = 'VERIFIED'
  or public.is_admin()
);

drop policy if exists businesses_owner_insert on public.businesses;
create policy businesses_owner_insert
on public.businesses
for insert
with check (
  owner_id = auth.uid()
  or public.is_admin()
);

drop policy if exists businesses_owner_update on public.businesses;
create policy businesses_owner_update
on public.businesses
for update
using (
  owner_id = auth.uid()
  or public.is_admin()
)
with check (
  owner_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- GUIDES POLICIES
-- =========================================================

drop policy if exists guides_owner_or_verified on public.guides;
create policy guides_owner_or_verified
on public.guides
for select
using (
  user_id = auth.uid()
  or verification_status = 'VERIFIED'
  or public.is_admin()
);

drop policy if exists guides_owner_insert on public.guides;
create policy guides_owner_insert
on public.guides
for insert
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists guides_owner_update on public.guides;
create policy guides_owner_update
on public.guides
for update
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- TRAVEL AGENCIES POLICIES
-- =========================================================

drop policy if exists travel_agencies_owner_or_verified on public.travel_agencies;
create policy travel_agencies_owner_or_verified
on public.travel_agencies
for select
using (
  owner_id = auth.uid()
  or verification_status = 'VERIFIED'
  or public.is_admin()
);

drop policy if exists travel_agencies_owner_insert on public.travel_agencies;
create policy travel_agencies_owner_insert
on public.travel_agencies
for insert
with check (
  owner_id = auth.uid()
  or public.is_admin()
);

drop policy if exists travel_agencies_owner_update on public.travel_agencies;
create policy travel_agencies_owner_update
on public.travel_agencies
for update
using (
  owner_id = auth.uid()
  or public.is_admin()
)
with check (
  owner_id = auth.uid()
  or public.is_admin()
);


-- =========================================================
-- NOTIFICATIONS POLICIES
-- =========================================================

drop policy if exists notifications_owner_select on public.notifications;
create policy notifications_owner_select
on public.notifications
for select
using (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists notifications_owner_update on public.notifications;
create policy notifications_owner_update
on public.notifications
for update
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists notifications_admin_insert on public.notifications;
create policy notifications_admin_insert
on public.notifications
for insert
with check (public.is_admin());

drop policy if exists notifications_admin_delete on public.notifications;
create policy notifications_admin_delete
on public.notifications
for delete
using (public.is_admin());


-- =========================================================
-- RECOMMENDATIONS POLICIES
-- =========================================================

drop policy if exists recommendations_owner_select on public.recommendations;
create policy recommendations_owner_select
on public.recommendations
for select
using (
  user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists recommendations_admin_insert on public.recommendations;
create policy recommendations_admin_insert
on public.recommendations
for insert
with check (public.is_admin());

drop policy if exists recommendations_admin_delete on public.recommendations;
create policy recommendations_admin_delete
on public.recommendations
for delete
using (public.is_admin());


-- =========================================================
-- AUDIT LOGS POLICIES
-- =========================================================

drop policy if exists audit_logs_admin_select on public.audit_logs;
create policy audit_logs_admin_select
on public.audit_logs
for select
using (public.is_admin());

drop policy if exists audit_logs_admin_insert on public.audit_logs;
create policy audit_logs_admin_insert
on public.audit_logs
for insert
with check (public.is_admin());


-- =========================================================
-- ANALYTICS POLICIES
-- =========================================================

drop policy if exists analytics_admin_select on public.analytics_events;
create policy analytics_admin_select
on public.analytics_events
for select
using (public.is_admin());

drop policy if exists analytics_authenticated_insert on public.analytics_events;
create policy analytics_authenticated_insert
on public.analytics_events
for insert
with check (
  auth.uid() is not null
  and (
    user_id = auth.uid()
    or user_id is null
  )
);


-- =========================================================
-- REPORTS POLICIES
-- =========================================================

drop policy if exists reports_reporter_or_admin_select on public.reports;
create policy reports_reporter_or_admin_select
on public.reports
for select
using (
  reporter_id = auth.uid()
  or public.is_admin()
);

drop policy if exists reports_reporter_insert on public.reports;
create policy reports_reporter_insert
on public.reports
for insert
with check (
  reporter_id = auth.uid()
  or public.is_admin()
);

drop policy if exists reports_admin_update on public.reports;
create policy reports_admin_update
on public.reports
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists reports_admin_delete on public.reports;
create policy reports_admin_delete
on public.reports
for delete
using (public.is_admin());


-- =========================================================
-- SAFETY ALERTS POLICIES
-- =========================================================

drop policy if exists safety_alerts_public_select on public.safety_alerts;
create policy safety_alerts_public_select
on public.safety_alerts
for select
using (active = true);

drop policy if exists safety_alerts_admin_insert on public.safety_alerts;
create policy safety_alerts_admin_insert
on public.safety_alerts
for insert
with check (public.is_admin());

drop policy if exists safety_alerts_admin_update on public.safety_alerts;
create policy safety_alerts_admin_update
on public.safety_alerts
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists safety_alerts_admin_delete on public.safety_alerts;
create policy safety_alerts_admin_delete
on public.safety_alerts
for delete
using (public.is_admin());


-- =========================================================
-- GRANTS
-- =========================================================

grant usage on schema public to anon, authenticated;

grant select on public.destinations to anon, authenticated;
grant select on public.listings to anon, authenticated;
grant select on public.events to anon, authenticated;
grant select on public.safety_alerts to anon, authenticated;

grant select, insert, update, delete
on public.profiles,
   public.trips,
   public.itineraries,
   public.bookings,
   public.reviews,
   public.favorites,
   public.contacts,
   public.businesses,
   public.guides,
   public.travel_agencies,
   public.notifications,
   public.recommendations,
   public.audit_logs,
   public.analytics_events,
   public.reports
to authenticated;

grant usage, select
on all sequences in schema public
to authenticated;


-- =========================================================
-- END TOURISM360 COMPLETE SCHEMA
-- =========================================================